### ISSUE TITLE
On which material & OS does your data come ?

### ISSUE THREAD

**Issue by abulmo** [FireFather/perft-speeds#1]
On which material & OS are your performance data recorded ?
Perft results depend a lot on the cpu, memory, graphics card and also on the OS installed on the computer.

**Comment by FireFather** [comment]
Nor sure what you mean by material?
OS is 64 bit Windows 11 Pro
Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
32.0 GB RAM
